spring:
  http:
    encoding:
      charset: utf-8

  thymeleaf:
    cache: false
  mvc:
    date-format: yyyy-MM-dd
  jackson:
    date-format: yyyy-MM-dd
    time-zone: GMT+8

server:
  port: 8089

  servlet:
    context-path: /gg