server:
  #服务器端口
  port: 8080
spring:
  #数据源
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.56.88:3306/db01?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
  thymeleaf:
    #取消页面缓存
    cache: false
  jackson:
    serialization:
      indent-output: true
mybatis:
  #配置别名所在包，自动扫描
  type-aliases-package: com.turing.sb.entity
  #配置mapper.xml所在包，自动扫描
  mapper-locations: classpath:mapper/*.xml